# Array Introduction:



Importing Numpy and Array Type.

In [106]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



Shape of an Array.

In [107]:
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
  print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



Reshaping an Array.

In [108]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


# Array Creation:

Arrays with evenly Spaced values - arange.

In [109]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


Arrays with evenly Spaced values - linspace.

In [110]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


Initializing an Array.

In [111]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.9e-324 9.9e-324]
 [1.5e-323 2.5e-323]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Converting list to array using np.array.

In [112]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


From shape of an existing array.

In [113]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[3.5e-323 4.0e-323 4.4e-323]
 [4.9e-323 5.4e-323 5.9e-323]]


Manipulatiing existing array.

In [114]:
import numpy as np
array = np.array([1, 2, 3])
# Multiplies each element by 2, result: [2, 4, 6]
print(array)
new_array = array * 2
print(new_array)
# Creates a new array with the same elements
copied_array = np.copy(array)
print(copied_array)
# Slices elements from index 1 to 3, result:[2]
sliced_array = array[1:2]
print(sliced_array)

[1 2 3]
[2 4 6]
[1 2 3]
[2]


 With Concatenating Operation.

In [115]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Concatenate along axis 0 (vertical) Shape: (4, 2)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Concatenate along axis 1 (horizontal) Shape: (2, 4)
print(concat_axis0, concat_axis1, sep='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


Sample Code for Indexing and Slicing.

In [116]:
import numpy as np
# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])
# Slicing examples
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])
# Output Basic: arr1d:[1 2 3] arr2d:[[3 4] [6 7]] arr3d:[[[5] [7]]]
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])
# Output: Step: [1 3] [[1] [7]] [[[1] [9]]]

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


# Array Mathematics:

Intriduction to ”ufuncs”.

In [117]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2)) # Output Add: [5 7 9]
print("Subtract:", np.subtract(arr1, arr2))
# Output Subtract: [-3 -3 -3]
print("Divide:", np.divide(arr1, arr2))
# Output Divide: [0.25 0.4 0.5 ]
print("Multiply:", np.multiply(arr1, arr2))
# Output Multiply: [ 4 10 18]
print("Power:", np.power(arr1, arr2))
# Output Power: [ 1 32 729]
print("Exp:", np.exp(arr1))
# Output Exp: [ 2.71828183 7.3890561 20.08553692]

Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


Using ”np.dot”

In [118]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape: (2, 2)

Result with np.dot:
 [[ 58  64]
 [139 154]]


Using ”np.matmul”.

In [119]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print("Result with @ operator:\n", result_at) # Output shape: (2, 2)
# Matrix multiplication using np.matmul
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul) # Output shape: (2, 2)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


# Linear Algebra with Numpy - np.linalg:

Common linear algebra operation with np.linalg.

In [120]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5 -0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant: -2.0
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Outptut: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A, B))
#Output: Solution x: [-4. 4.5]

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


# TO - DO - Task

## Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [121]:
import numpy as np

In [122]:
a=np.empty((2,2))
print(a)
b=np.ones((4,2))
print(b)
c=np.full((2,2),4)
print(c)
d=np.zeros_like(c)
print(d)
e=np.ones_like(c)
print(e)
new_list = [1,2,3,4]
f=np.array(new_list)
print(f)


[[1. 2.]
 [3. 4.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[4 4]
 [4 4]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [123]:
g=np.arange(10,50)
print(g)
h=np.random.random(30)
print(h)
i=h.mean()
print(i)
j=np.random.random((10,10))
print(j)
k=j.max()
l=j.min()
print("Maximum Vlaue ",k,"minimum value ",l)
m=np.zeros(10)
m[4]=1
print(m)
n=np.array([1,2,0,0,4,0])
print(n)
rev = n[::-1]
print(rev)
o=np.ones((5,5))
o[1:-1,1:-1]=0
print(o)
p=np.random.randint(0,10,(8,8))
p[::2,::2]=1
p[1::2,1::2]=1
p[::2, 1::2]=0
p[1::2,::2]=0
print(p)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[0.43898742 0.8447786  0.31477201 0.23572721 0.83954979 0.01023895
 0.4573345  0.35413858 0.69931046 0.08219075 0.75995052 0.03324225
 0.92827565 0.67806536 0.63742563 0.56049983 0.81792095 0.72563119
 0.97721061 0.42239551 0.24834806 0.42289013 0.68968168 0.51266017
 0.60447635 0.95021743 0.66761786 0.00817376 0.41479242 0.74622832]
0.5360910641554855
[[0.22623385 0.46966343 0.47505693 0.13749148 0.26151086 0.65242884
  0.71958529 0.98176934 0.51282471 0.37102159]
 [0.0186891  0.20697566 0.91987545 0.49928191 0.14003326 0.19453392
  0.67515984 0.22284704 0.22650109 0.06672368]
 [0.13212256 0.46739223 0.60407109 0.16410491 0.83204033 0.4405892
  0.57880547 0.65248091 0.58251258 0.13458016]
 [0.01993633 0.52823662 0.11455784 0.06348734 0.70507517 0.0161766
  0.48143275 0.58777123 0.30337927 0.18801667]
 [0.95541829 0.13148154 0.25143391 0.25061485 0.17010736 0.59160

Problem - 3: Array Operations:
For the following arrays:



x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);



v = np.array([9,10]) and w = np.array([11,12]);


Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [160]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);
print("Add", np.add(x,y))
print("Add", np.add(v,w))
print("Subtract", np.subtract(x,y))
print("Subtract", np.subtract(v,w))
print("Multiply", np.multiply(x,y))
print("Multiply", np.multiply(v,w))
print("Square", np.square(x))
print("Square", np.square(y))
print("Square", np.square(v))
print("Square", np.square(w))
print("Dot Product", np.dot(v,w))
print("Dot Product", np.dot(x,v))
print("Dot Product", np.dot(x,y))
print("Concatenate", np.concatenate((x,y),axis=1))
print("Concatenate", np.concatenate((v,w),axis=0))
print("Concatenate", np.concatenate((x,v),axis=0))

Add [[ 6  8]
 [10 13]]
Add [20 22]
Subtract [[-4 -4]
 [-4 -3]]
Subtract [-2 -2]
Multiply [[ 5 12]
 [21 40]]
Multiply [ 99 120]
Square [[ 1  4]
 [ 9 25]]
Square [[25 36]
 [49 64]]
Square [ 81 100]
Square [121 144]
Dot Product 219
Dot Product [29 77]
Dot Product [[19 22]
 [50 58]]
Concatenate [[1 2 5 6]
 [3 5 7 8]]
Concatenate [ 9 10 11 12]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

=> I cannot concatenate x and v as x has 2 dimentions and v has 1 dimentions and to concatenate we must have same number of dimentions.

Problem - 4: Matrix Operations:


• For the following arrays:


A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);


Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1


x − y + 2z = −3


3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [125]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AInverse = np.linalg.inv(A)
print(np.dot(A, AInverse).astype(int))
if np.array_equal(np.dot(A,B), np.dot(B,A)):
    print("AB=BA")
else:
    print("AB!=BA")
AdotB=np.dot(A,B)
AT=np.transpose(A)
BT=np.transpose(B)
ABT=np.transpose(AdotB)
BTAT=np.dot(BT,AT)
if np.array_equal(BTAT, ABT):
    print("BTAT=ABT")


[[1 0]
 [0 0]]
AB!=BA
BTAT=ABT


In [126]:
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([[-1],[-3],[9]])
AInv=np.linalg.inv(A)
X=np.matmul(AInv,B)
print("X =",X[0],"Y =",X[1],"Z =")

X = [2.] Y = [1.] Z =


# 4.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:

   • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.


   • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [140]:
import time
import random
size=1000000
start_time = time.time()
list1=[]
list2=[]
for _ in range(1000000):
  list1.append(random.randint(0,101))
  list2.append(random.randint(0,101))
list3 = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Total Time Taken = ",end_time-start_time,"Seconds")

Total Time Taken =  1.2060682773590088 Seconds


In [139]:
start_time = time.time()
arr1 = np.random.randint(0, 101, size=size)
arr2 = np.random.randint(0, 101, size=size)
result = arr1 + arr2
end_time = time.time()

print("Time taken for element-wise addition (NumPy arrays):", end_time - start_time, "seconds")


Time taken for element-wise addition (NumPy arrays): 0.08867144584655762 seconds


2. Element-wise Multiplication

    • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

    • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [142]:
size=1000000
start_time = time.time()
list1=[]
list2=[]
for _ in range(1000000):
  list1.append(random.randint(0,101))
  list2.append(random.randint(0,101))
list3 = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("Total Time Taken = ",end_time-start_time,"Seconds")

Total Time Taken =  1.263622760772705 Seconds


In [141]:
start_time = time.time()
arr1 = np.random.randint(0, 101, size=size)
arr2 = np.random.randint(0, 101, size=size)
result = arr1 * arr2
end_time = time.time()

print("Time taken for element-wise addition (NumPy arrays):", end_time - start_time, "seconds")

Time taken for element-wise addition (NumPy arrays): 0.022687911987304688 seconds


3. Dot Product

    • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

    • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [159]:
size=1000
start_time = time.time()
lists=[]
list1=[]
list2=[]
for _ in range(size):
    list1.append([random.randint(0, 101) for _ in range(size)])
    list2.append([random.randint(0, 101) for _ in range(size)])

list3 = [[sum(list1[i][k] * list2[k][j] for k in range(len(list2))) for j in range(len(list2[0]))]for i in range(len(list1))]


end_time = time.time()
print("Total Time Taken = ",end_time-start_time,"Seconds")

Total Time Taken =  150.487446308136 Seconds


In [152]:
start_time = time.time()
arr1 = np.random.randint(0, 101, size=size)
arr2 = np.random.randint(0, 101, size=size)
result = np.dot(arr1,arr2)
end_time = time.time()

print("Time taken for element-wise addition (NumPy arrays):", end_time - start_time, "seconds")

Time taken for element-wise addition (NumPy arrays): 0.0010595321655273438 seconds


4. Matrix Multiplication


    • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

    • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [157]:
size=1000
start_time = time.time()
list1=[]
list2=[]
for _ in range(size):
    list1.append([random.randint(0, 101) for _ in range(size)])
    list2.append([random.randint(0, 101) for _ in range(size)])
list3 = [[sum(list1[i][k] * list2[k][j] for k in range(len(list2))) for j in range(len(list2[0]))]for i in range(len(list1))]
end_time = time.time()
print("Total Time Taken = ",end_time-start_time,"Seconds")

Total Time Taken =  152.3176929950714 Seconds


In [158]:
start_time = time.time()
arr1 = np.random.randint(0, 101, size=size)
arr2 = np.random.randint(0, 101, size=size)
result = np.matmul(arr1,arr2)
end_time = time.time()

print("Time taken for element-wise addition (NumPy arrays):", end_time - start_time, "seconds")

Time taken for element-wise addition (NumPy arrays): 0.006377220153808594 seconds
